// Build the shipped FTA knowledge-base asset from the curated method chunks.
// Default path is LEXICAL retrieval (no API, air-gap-safe): we ship the chunk
// text and match in-browser. OPTIONAL upgrade: set an embeddings endpoint and
// add a `.vec` to each chunk for semantic retrieval (left as a no-op here).
import fs from 'fs';
import path from 'path';
const here = path.dirname(new URL(import.meta.url).pathname);
const chunks = JSON.parse(fs.readFileSync(path.join(here, 'fta_kb_chunks.json'), 'utf8'));
const payload = { version: 1, builtAt: new Date().toISOString(), method: 'lexical', chunks };
const out = '/* AUTO-GENERATED by kb/build_fta_kb.mjs — do not edit by hand. */\n'
          + 'window.SL_FTA_KB = ' + JSON.stringify(payload) + ';\n';
fs.writeFileSync(path.join(here, '..', 'fta_kb_data.js'), out);
console.log('wrote fta_kb_data.js —', chunks.length, 'chunks,', out.length, 'bytes');
