(function(){"use strict";const VOLATILE_TOP=new Set(["_betaBuild"]);function deepDiff(a,b,cap){const out=[];cap=cap||25;const push=(path,va,vb)=>{if(out.length>=cap)return;const show=v=>{if(v===void 0)return"(missing)";try{const s=JSON.stringify(v);return s&&s.length>60?s.slice(0,57)+"…":s}catch{return String(v)}};out.push({path:path||"(root)",a:show(va),b:show(vb)})};return(function walk(x,y,path){if(out.length>=cap||x===y)return;const tx=Object.prototype.toString.call(x),ty=Object.prototype.toString.call(y);if(tx!==ty){push(path,x,y);return}if(Array.isArray(x)){x.length!==y.length&&push(path+".length",x.length,y.length);const n=Math.min(x.length,y.length);for(let i=0;i<n;i++)walk(x[i],y[i],path+"["+i+"]");return}if(x&&typeof x=="object"){new Set([...Object.keys(x),...Object.keys(y)]).forEach(k=>walk(x[k],y[k],path?path+"."+k:k));return}typeof x=="number"&&typeof y=="number"&&isNaN(x)&&isNaN(y)||push(path,x,y)})(a,b,""),out}function _strip(snap){const s=Object.assign({},snap);return VOLATILE_TOP.forEach(k=>{delete s[k]}),s}function rtProve(opts){if(opts=opts||{},typeof _slabBuildProjectExport!="function"||typeof _applyProjectData!="function")throw new Error("serializer pair unavailable");if(!opts.skipRing)try{typeof window._ringCapture=="function"&&window._ringCapture()}catch{}const t0=Date.now(),A=_slabBuildProjectExport(),aJson=JSON.stringify(A);_applyProjectData(JSON.parse(aJson));const C=_slabBuildProjectExport(),mismatches=deepDiff(_strip(A),_strip(C),25),result={at:new Date().toISOString(),ok:mismatches.length===0,bytes:aJson.length,ms:Date.now()-t0,mismatches,stores:Object.keys(A).length};try{typeof projectConfig<"u"&&(projectConfig.rtProofLast={at:result.at,ok:result.ok,bytes:result.bytes,stores:result.stores,mismatches:mismatches.map(m=>m.path)},typeof scheduleAutosave=="function"&&scheduleAutosave())}catch{}return result}window.rtProveUi=function(){if(confirm(`Prove the save/load round-trip?

The live project is serialized, re-applied through the exact refresh path, and re-serialized — any field that fails to survive is named. The pre-proof state is captured to the recovery ring first.`))try{const r=rtProve();r.ok?alert(`ROUND-TRIP PROVEN ✓

`+r.stores+" top-level stores · "+Math.round(r.bytes/1024)+" KB · "+r.ms+` ms
Every field survived serialize → apply → serialize.`):alert("ROUND-TRIP FAILED — "+r.mismatches.length+` field(s) did not survive:

`+r.mismatches.slice(0,8).map(m=>"· "+m.path+`
    saved: `+m.a+`
    after: `+m.b).join(`
`)+`

These fields would be lost on refresh. The pre-proof state is in the recovery ring.`);try{renderGtIntegrityPage()}catch{}}catch(e){alert("Proof failed to run: "+e.message)}};function _injectProofPanel(){const host=document.getElementById("gt-integrity-host");if(!host||document.getElementById("gt-rtproof-panel"))return;const last=typeof projectConfig<"u"&&projectConfig.rtProofLast||null,div=document.createElement("div");div.id="gt-rtproof-panel",div.innerHTML='<div style="border:1px solid var(--color-border-strong); background:var(--color-surface-1); margin-top:18px;"><div style="padding:9px 14px; border-bottom:2px solid var(--color-text-primary); display:flex; justify-content:space-between; align-items:center;"><b>Save/load round-trip proof</b><button class="ckpt-m-btn" style="font-size:11px; padding:2px 10px;" onclick="rtProveUi()">Prove round-trip…</button></div><p style="font-size:12px; color:var(--color-text-secondary); padding:8px 14px 4px;">Serialize → apply through the exact refresh path → serialize → deep-compare. A store that stops surviving is named here before it can lose work quietly. The regression suite runs the same proof on every release.</p><p class="u-mono" style="font-size:11px; padding:0 14px 10px;'+(last&&!last.ok?" color:#8E2A2A; font-weight:600;":" color:var(--color-text-tertiary);")+'">'+(last?"Last proof "+last.at.slice(0,16).replace("T"," ")+" — "+(last.ok?"PROVEN ✓ ("+last.stores+" stores, "+Math.round(last.bytes/1024)+" KB)":"FAILED: "+last.mismatches.slice(0,4).join(", ")+(last.mismatches.length>4?" +"+(last.mismatches.length-4):"")):"Not yet run on this project.")+"</p></div>",host.appendChild(div)}(function(){if(typeof window.switchTab=="function"&&!window.switchTab._rtProofWrapped){const orig=window.switchTab,wrapped=function(tabId){const r=orig.apply(this,arguments);try{tabId==="gt-integrity"&&setTimeout(()=>{_injectProofPanel()},80)}catch{}return r};wrapped._rtProofWrapped=!0,window.switchTab=wrapped}})(),window.rtProve=rtProve,window._rtDeepDiff=deepDiff})();
